services:
    voting:
        container_name: vedtatt.drift.tihlde.org
        build:
            context: .
        restart: unless-stopped
        ports:
          - ${BIND_IP_ADDRESS:-127.0.0.1}:3000:3000
        env_file: .env
