services:
  
  votingdb:
    image: postgres
    container_name: votingdb
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: votingdb
    ports:
      - "5432:5432"
    volumes:
      - votingdb_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]  
    restart: always
  backend:
    depends_on:
      - redis
      - votingdb
    env_file:
      - ./voting-backend/.env.docker
    build:
      context: ./voting-backend
    ports:
      - "4000:4000"
    volumes:
      - ./voting-backend:/app
  frontend:
    depends_on:
      - backend
    env_file:
      - ./voting-frontend/.env.docker
    build:
      context: ./voting-frontend
    ports:
      - "80:3000"
    volumes:
      - ./voting-frontend:/app


volumes:
  votingdb_data:
  redis_data:
