services:
    voting:
        container_name: vedtatt.drift.tihlde.org
        build:
            context: .
            no_cache: true
        restart: unless-stopped
        ports:
            - "3000:3000"
        env_file: .env
