FROM oven/bun:1 AS base
WORKDIR /usr/src/app

# Install stage - uses the pruned lockfile
FROM base AS install
WORKDIR /usr/src/app

# Copy the json structure generated by turbo prune
COPY package.json .
COPY bun.lock ./bun.lock
# Install the dependencies
RUN bun install

# Build stage
FROM base AS build
# Copy the installed node_modules (all of them, including workspace packages)
COPY . .
COPY --from=install /usr/src/app/ .
ENV NODE_ENV=production
ENV NITRO_PRESET=bun
RUN bun run build

# Final image
FROM oven/bun:1-slim AS release
WORKDIR /usr/src/app
COPY --from=build /usr/src/app/.output ./.output
COPY --from=install /usr/src/app/node_modules ./node_modules

USER bun
EXPOSE 3000/tcp
ENTRYPOINT ["bun", "run", "./.output/server/index.mjs"]
