/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as ApiSseRouteImport } from './routes/api/sse'
import { Route as AuthenticatedJoinMeetingIdRouteImport } from './routes/_authenticated/join.$meetingId'
import { Route as AuthenticatedMeetingsIndexRouteImport } from './routes/_authenticated/meetings/index'
import { Route as AuthenticatedMeetingsMeetingIdRouteImport } from './routes/_authenticated/meetings/$meetingId'
import { Route as AuthenticatedMeetingsNewRouteImport } from './routes/_authenticated/meetings/new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedMeetingsMeetingIdIndexRouteImport } from './routes/_authenticated/meetings/$meetingId/index'
import { Route as AuthenticatedMeetingsMeetingIdEditRouteImport } from './routes/_authenticated/meetings/$meetingId/edit'
import { Route as AuthenticatedMeetingsMeetingIdPresentRouteImport } from './routes/_authenticated/meetings/$meetingId/present'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiSseRoute = ApiSseRouteImport.update({
  id: '/api/sse',
  path: '/api/sse',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedJoinMeetingIdRoute =
  AuthenticatedJoinMeetingIdRouteImport.update({
    id: '/join/$meetingId',
    path: '/join/$meetingId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMeetingsIndexRoute =
  AuthenticatedMeetingsIndexRouteImport.update({
    id: '/meetings/',
    path: '/meetings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMeetingsMeetingIdRoute =
  AuthenticatedMeetingsMeetingIdRouteImport.update({
    id: '/meetings/$meetingId',
    path: '/meetings/$meetingId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMeetingsNewRoute =
  AuthenticatedMeetingsNewRouteImport.update({
    id: '/meetings/new',
    path: '/meetings/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMeetingsMeetingIdIndexRoute =
  AuthenticatedMeetingsMeetingIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMeetingsMeetingIdRoute,
  } as any)
const AuthenticatedMeetingsMeetingIdEditRoute =
  AuthenticatedMeetingsMeetingIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedMeetingsMeetingIdRoute,
  } as any)
const AuthenticatedMeetingsMeetingIdPresentRoute =
  AuthenticatedMeetingsMeetingIdPresentRouteImport.update({
    id: '/present',
    path: '/present',
    getParentRoute: () => AuthenticatedMeetingsMeetingIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/api/sse': typeof ApiSseRoute
  '/join/$meetingId': typeof AuthenticatedJoinMeetingIdRoute
  '/meetings/$meetingId': typeof AuthenticatedMeetingsMeetingIdRouteWithChildren
  '/meetings/new': typeof AuthenticatedMeetingsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/meetings/': typeof AuthenticatedMeetingsIndexRoute
  '/meetings/$meetingId/edit': typeof AuthenticatedMeetingsMeetingIdEditRoute
  '/meetings/$meetingId/present': typeof AuthenticatedMeetingsMeetingIdPresentRoute
  '/meetings/$meetingId/': typeof AuthenticatedMeetingsMeetingIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/api/sse': typeof ApiSseRoute
  '/join/$meetingId': typeof AuthenticatedJoinMeetingIdRoute
  '/meetings/new': typeof AuthenticatedMeetingsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/meetings': typeof AuthenticatedMeetingsIndexRoute
  '/meetings/$meetingId/edit': typeof AuthenticatedMeetingsMeetingIdEditRoute
  '/meetings/$meetingId/present': typeof AuthenticatedMeetingsMeetingIdPresentRoute
  '/meetings/$meetingId': typeof AuthenticatedMeetingsMeetingIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/api/sse': typeof ApiSseRoute
  '/_authenticated/join/$meetingId': typeof AuthenticatedJoinMeetingIdRoute
  '/_authenticated/meetings/$meetingId': typeof AuthenticatedMeetingsMeetingIdRouteWithChildren
  '/_authenticated/meetings/new': typeof AuthenticatedMeetingsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authenticated/meetings/': typeof AuthenticatedMeetingsIndexRoute
  '/_authenticated/meetings/$meetingId/edit': typeof AuthenticatedMeetingsMeetingIdEditRoute
  '/_authenticated/meetings/$meetingId/present': typeof AuthenticatedMeetingsMeetingIdPresentRoute
  '/_authenticated/meetings/$meetingId/': typeof AuthenticatedMeetingsMeetingIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/profile'
    | '/api/sse'
    | '/join/$meetingId'
    | '/meetings/$meetingId'
    | '/meetings/new'
    | '/api/auth/$'
    | '/meetings/'
    | '/meetings/$meetingId/edit'
    | '/meetings/$meetingId/present'
    | '/meetings/$meetingId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/profile'
    | '/api/sse'
    | '/join/$meetingId'
    | '/meetings/new'
    | '/api/auth/$'
    | '/meetings'
    | '/meetings/$meetingId/edit'
    | '/meetings/$meetingId/present'
    | '/meetings/$meetingId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/profile'
    | '/api/sse'
    | '/_authenticated/join/$meetingId'
    | '/_authenticated/meetings/$meetingId'
    | '/_authenticated/meetings/new'
    | '/api/auth/$'
    | '/_authenticated/meetings/'
    | '/_authenticated/meetings/$meetingId/edit'
    | '/_authenticated/meetings/$meetingId/present'
    | '/_authenticated/meetings/$meetingId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiSseRoute: typeof ApiSseRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/sse': {
      id: '/api/sse'
      path: '/api/sse'
      fullPath: '/api/sse'
      preLoaderRoute: typeof ApiSseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/join/$meetingId': {
      id: '/_authenticated/join/$meetingId'
      path: '/join/$meetingId'
      fullPath: '/join/$meetingId'
      preLoaderRoute: typeof AuthenticatedJoinMeetingIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/meetings/': {
      id: '/_authenticated/meetings/'
      path: '/meetings'
      fullPath: '/meetings/'
      preLoaderRoute: typeof AuthenticatedMeetingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/meetings/$meetingId': {
      id: '/_authenticated/meetings/$meetingId'
      path: '/meetings/$meetingId'
      fullPath: '/meetings/$meetingId'
      preLoaderRoute: typeof AuthenticatedMeetingsMeetingIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/meetings/new': {
      id: '/_authenticated/meetings/new'
      path: '/meetings/new'
      fullPath: '/meetings/new'
      preLoaderRoute: typeof AuthenticatedMeetingsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/meetings/$meetingId/': {
      id: '/_authenticated/meetings/$meetingId/'
      path: '/'
      fullPath: '/meetings/$meetingId/'
      preLoaderRoute: typeof AuthenticatedMeetingsMeetingIdIndexRouteImport
      parentRoute: typeof AuthenticatedMeetingsMeetingIdRoute
    }
    '/_authenticated/meetings/$meetingId/edit': {
      id: '/_authenticated/meetings/$meetingId/edit'
      path: '/edit'
      fullPath: '/meetings/$meetingId/edit'
      preLoaderRoute: typeof AuthenticatedMeetingsMeetingIdEditRouteImport
      parentRoute: typeof AuthenticatedMeetingsMeetingIdRoute
    }
    '/_authenticated/meetings/$meetingId/present': {
      id: '/_authenticated/meetings/$meetingId/present'
      path: '/present'
      fullPath: '/meetings/$meetingId/present'
      preLoaderRoute: typeof AuthenticatedMeetingsMeetingIdPresentRouteImport
      parentRoute: typeof AuthenticatedMeetingsMeetingIdRoute
    }
  }
}

interface AuthenticatedMeetingsMeetingIdRouteChildren {
  AuthenticatedMeetingsMeetingIdEditRoute: typeof AuthenticatedMeetingsMeetingIdEditRoute
  AuthenticatedMeetingsMeetingIdPresentRoute: typeof AuthenticatedMeetingsMeetingIdPresentRoute
  AuthenticatedMeetingsMeetingIdIndexRoute: typeof AuthenticatedMeetingsMeetingIdIndexRoute
}

const AuthenticatedMeetingsMeetingIdRouteChildren: AuthenticatedMeetingsMeetingIdRouteChildren =
  {
    AuthenticatedMeetingsMeetingIdEditRoute:
      AuthenticatedMeetingsMeetingIdEditRoute,
    AuthenticatedMeetingsMeetingIdPresentRoute:
      AuthenticatedMeetingsMeetingIdPresentRoute,
    AuthenticatedMeetingsMeetingIdIndexRoute:
      AuthenticatedMeetingsMeetingIdIndexRoute,
  }

const AuthenticatedMeetingsMeetingIdRouteWithChildren =
  AuthenticatedMeetingsMeetingIdRoute._addFileChildren(
    AuthenticatedMeetingsMeetingIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedJoinMeetingIdRoute: typeof AuthenticatedJoinMeetingIdRoute
  AuthenticatedMeetingsMeetingIdRoute: typeof AuthenticatedMeetingsMeetingIdRouteWithChildren
  AuthenticatedMeetingsNewRoute: typeof AuthenticatedMeetingsNewRoute
  AuthenticatedMeetingsIndexRoute: typeof AuthenticatedMeetingsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedJoinMeetingIdRoute: AuthenticatedJoinMeetingIdRoute,
  AuthenticatedMeetingsMeetingIdRoute:
    AuthenticatedMeetingsMeetingIdRouteWithChildren,
  AuthenticatedMeetingsNewRoute: AuthenticatedMeetingsNewRoute,
  AuthenticatedMeetingsIndexRoute: AuthenticatedMeetingsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiSseRoute: ApiSseRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
