/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedMeetingsRouteImport } from './routes/_authenticated/meetings'
import { Route as AuthenticatedMeetingsIndexRouteImport } from './routes/_authenticated/meetings.index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedMeetingsNewRouteImport } from './routes/_authenticated/meetings.new'
import { Route as AuthenticatedMeetingsMeetingIdRouteImport } from './routes/_authenticated/meetings.$meetingId'
import { Route as AuthenticatedMeetingsMeetingIdIndexRouteImport } from './routes/_authenticated/meetings.$meetingId/index'
import { Route as AuthenticatedMeetingsMeetingIdRegisterRouteImport } from './routes/_authenticated/meetings.$meetingId_.register'
import { Route as AuthenticatedMeetingsMeetingIdEditRouteImport } from './routes/_authenticated/meetings.$meetingId/edit'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeetingsRoute = AuthenticatedMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeetingsIndexRoute =
  AuthenticatedMeetingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMeetingsRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMeetingsNewRoute =
  AuthenticatedMeetingsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedMeetingsRoute,
  } as any)
const AuthenticatedMeetingsMeetingIdRoute =
  AuthenticatedMeetingsMeetingIdRouteImport.update({
    id: '/$meetingId',
    path: '/$meetingId',
    getParentRoute: () => AuthenticatedMeetingsRoute,
  } as any)
const AuthenticatedMeetingsMeetingIdIndexRoute =
  AuthenticatedMeetingsMeetingIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMeetingsMeetingIdRoute,
  } as any)
const AuthenticatedMeetingsMeetingIdRegisterRoute =
  AuthenticatedMeetingsMeetingIdRegisterRouteImport.update({
    id: '/$meetingId_/register',
    path: '/$meetingId/register',
    getParentRoute: () => AuthenticatedMeetingsRoute,
  } as any)
const AuthenticatedMeetingsMeetingIdEditRoute =
  AuthenticatedMeetingsMeetingIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedMeetingsMeetingIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/meetings': typeof AuthenticatedMeetingsRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/meetings/$meetingId': typeof AuthenticatedMeetingsMeetingIdRouteWithChildren
  '/meetings/new': typeof AuthenticatedMeetingsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/meetings/': typeof AuthenticatedMeetingsIndexRoute
  '/meetings/$meetingId/edit': typeof AuthenticatedMeetingsMeetingIdEditRoute
  '/meetings/$meetingId/register': typeof AuthenticatedMeetingsMeetingIdRegisterRoute
  '/meetings/$meetingId/': typeof AuthenticatedMeetingsMeetingIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/meetings/new': typeof AuthenticatedMeetingsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/meetings': typeof AuthenticatedMeetingsIndexRoute
  '/meetings/$meetingId/edit': typeof AuthenticatedMeetingsMeetingIdEditRoute
  '/meetings/$meetingId/register': typeof AuthenticatedMeetingsMeetingIdRegisterRoute
  '/meetings/$meetingId': typeof AuthenticatedMeetingsMeetingIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/meetings': typeof AuthenticatedMeetingsRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/meetings/$meetingId': typeof AuthenticatedMeetingsMeetingIdRouteWithChildren
  '/_authenticated/meetings/new': typeof AuthenticatedMeetingsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authenticated/meetings/': typeof AuthenticatedMeetingsIndexRoute
  '/_authenticated/meetings/$meetingId/edit': typeof AuthenticatedMeetingsMeetingIdEditRoute
  '/_authenticated/meetings/$meetingId_/register': typeof AuthenticatedMeetingsMeetingIdRegisterRoute
  '/_authenticated/meetings/$meetingId/': typeof AuthenticatedMeetingsMeetingIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/meetings'
    | '/profile'
    | '/meetings/$meetingId'
    | '/meetings/new'
    | '/api/auth/$'
    | '/meetings/'
    | '/meetings/$meetingId/edit'
    | '/meetings/$meetingId/register'
    | '/meetings/$meetingId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/profile'
    | '/meetings/new'
    | '/api/auth/$'
    | '/meetings'
    | '/meetings/$meetingId/edit'
    | '/meetings/$meetingId/register'
    | '/meetings/$meetingId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/meetings'
    | '/_authenticated/profile'
    | '/_authenticated/meetings/$meetingId'
    | '/_authenticated/meetings/new'
    | '/api/auth/$'
    | '/_authenticated/meetings/'
    | '/_authenticated/meetings/$meetingId/edit'
    | '/_authenticated/meetings/$meetingId_/register'
    | '/_authenticated/meetings/$meetingId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/meetings': {
      id: '/_authenticated/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof AuthenticatedMeetingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/meetings/': {
      id: '/_authenticated/meetings/'
      path: '/'
      fullPath: '/meetings/'
      preLoaderRoute: typeof AuthenticatedMeetingsIndexRouteImport
      parentRoute: typeof AuthenticatedMeetingsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/meetings/new': {
      id: '/_authenticated/meetings/new'
      path: '/new'
      fullPath: '/meetings/new'
      preLoaderRoute: typeof AuthenticatedMeetingsNewRouteImport
      parentRoute: typeof AuthenticatedMeetingsRoute
    }
    '/_authenticated/meetings/$meetingId': {
      id: '/_authenticated/meetings/$meetingId'
      path: '/$meetingId'
      fullPath: '/meetings/$meetingId'
      preLoaderRoute: typeof AuthenticatedMeetingsMeetingIdRouteImport
      parentRoute: typeof AuthenticatedMeetingsRoute
    }
    '/_authenticated/meetings/$meetingId/': {
      id: '/_authenticated/meetings/$meetingId/'
      path: '/'
      fullPath: '/meetings/$meetingId/'
      preLoaderRoute: typeof AuthenticatedMeetingsMeetingIdIndexRouteImport
      parentRoute: typeof AuthenticatedMeetingsMeetingIdRoute
    }
    '/_authenticated/meetings/$meetingId_/register': {
      id: '/_authenticated/meetings/$meetingId_/register'
      path: '/$meetingId/register'
      fullPath: '/meetings/$meetingId/register'
      preLoaderRoute: typeof AuthenticatedMeetingsMeetingIdRegisterRouteImport
      parentRoute: typeof AuthenticatedMeetingsRoute
    }
    '/_authenticated/meetings/$meetingId/edit': {
      id: '/_authenticated/meetings/$meetingId/edit'
      path: '/edit'
      fullPath: '/meetings/$meetingId/edit'
      preLoaderRoute: typeof AuthenticatedMeetingsMeetingIdEditRouteImport
      parentRoute: typeof AuthenticatedMeetingsMeetingIdRoute
    }
  }
}

interface AuthenticatedMeetingsMeetingIdRouteChildren {
  AuthenticatedMeetingsMeetingIdEditRoute: typeof AuthenticatedMeetingsMeetingIdEditRoute
  AuthenticatedMeetingsMeetingIdIndexRoute: typeof AuthenticatedMeetingsMeetingIdIndexRoute
}

const AuthenticatedMeetingsMeetingIdRouteChildren: AuthenticatedMeetingsMeetingIdRouteChildren =
  {
    AuthenticatedMeetingsMeetingIdEditRoute:
      AuthenticatedMeetingsMeetingIdEditRoute,
    AuthenticatedMeetingsMeetingIdIndexRoute:
      AuthenticatedMeetingsMeetingIdIndexRoute,
  }

const AuthenticatedMeetingsMeetingIdRouteWithChildren =
  AuthenticatedMeetingsMeetingIdRoute._addFileChildren(
    AuthenticatedMeetingsMeetingIdRouteChildren,
  )

interface AuthenticatedMeetingsRouteChildren {
  AuthenticatedMeetingsMeetingIdRoute: typeof AuthenticatedMeetingsMeetingIdRouteWithChildren
  AuthenticatedMeetingsNewRoute: typeof AuthenticatedMeetingsNewRoute
  AuthenticatedMeetingsIndexRoute: typeof AuthenticatedMeetingsIndexRoute
  AuthenticatedMeetingsMeetingIdRegisterRoute: typeof AuthenticatedMeetingsMeetingIdRegisterRoute
}

const AuthenticatedMeetingsRouteChildren: AuthenticatedMeetingsRouteChildren = {
  AuthenticatedMeetingsMeetingIdRoute:
    AuthenticatedMeetingsMeetingIdRouteWithChildren,
  AuthenticatedMeetingsNewRoute: AuthenticatedMeetingsNewRoute,
  AuthenticatedMeetingsIndexRoute: AuthenticatedMeetingsIndexRoute,
  AuthenticatedMeetingsMeetingIdRegisterRoute:
    AuthenticatedMeetingsMeetingIdRegisterRoute,
}

const AuthenticatedMeetingsRouteWithChildren =
  AuthenticatedMeetingsRoute._addFileChildren(
    AuthenticatedMeetingsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedMeetingsRoute: typeof AuthenticatedMeetingsRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedMeetingsRoute: AuthenticatedMeetingsRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
